/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patenio.dentalapp;
import admin.adminDashboard;
import config.Session;
import config.connectDB;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import user.usersDashboard;

/**
 *
 * @author SCC-COLLEGE
 */
public class loginForm extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
    public loginForm() {
        initComponents();
    }
    static String type;
    static String status;
    public static boolean loginUser(String email, String pass){
        connectDB con= new connectDB();
        try{
        String query = "SELECT * FROM tbl_user WHERE email='" +email+ "' AND pass='"+pass+ "'";
        ResultSet resultSet=con.getData(query);
        
        if(resultSet.next()){
            type=resultSet.getString("u_type");
            status=resultSet.getString("status");   
            
//        Session sess=Session.getInstance();
//        sess.setUid(resultSet.getInt("u_id"));
//        sess.setFname(resultSet.getString("fname"));
//        sess.setFname(resultSet.getString("lname"));
//        sess.setFname(resultSet.getString("email"));
//        sess.setFname(resultSet.getString("type"));
//        sess.setFname(resultSet.getString("status"));
//            System.out.println(""+sess.getUid());
            return true;
        }else{
            return false;      
        }
        
        }catch (SQLException ex){
            return false;
        }
        
    }
    
  Color bg1 = new Color (153,153,153);
  Color login_b= new Color (82,107,136);
  Color bg= new Color (42,82,129);
  Color signup= new Color (122,122,122);
  Color signup_1= new Color (167,167,167);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        signUp = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        logIn = new javax.swing.JLabel();
        sign_upbt = new javax.swing.JPanel();
        sign_up = new javax.swing.JLabel();
        register_acc = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        pass_label = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        login_layout1 = new javax.swing.JPanel();
        login_button1 = new javax.swing.JLabel();
        cancel = new javax.swing.JPanel();
        cancel_button = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        signUp.setBackground(new java.awt.Color(42, 82, 129));
        signUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(213, 220, 233));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plain_logo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 480, 220));

        logIn.setBackground(new java.awt.Color(42, 82, 129));
        logIn.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        logIn.setForeground(new java.awt.Color(42, 82, 129));
        logIn.setText("LOGIN FORM");
        jPanel1.add(logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        sign_upbt.setBackground(new java.awt.Color(122, 122, 122));
        sign_upbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_upbtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sign_upbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sign_upbtMouseExited(evt);
            }
        });
        sign_upbt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sign_up.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        sign_up.setForeground(new java.awt.Color(255, 255, 255));
        sign_up.setText("SIGN UP");
        sign_upbt.add(sign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(sign_upbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 110, 40));

        register_acc.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        register_acc.setText("I don't have an account");
        jPanel1.add(register_acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        email.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 260, 40));

        email_label.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        email_label.setText("EMAIL");
        jPanel1.add(email_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        pass_label.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        pass_label.setText("PASSWORD");
        jPanel1.add(pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        pass.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 260, 40));

        login_layout1.setBackground(new java.awt.Color(42, 82, 129));
        login_layout1.setForeground(new java.awt.Color(42, 82, 129));
        login_layout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_layout1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_layout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_layout1MouseExited(evt);
            }
        });
        login_layout1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_button1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        login_button1.setForeground(new java.awt.Color(255, 255, 255));
        login_button1.setText("LOGIN");
        login_layout1.add(login_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 60, -1));

        jPanel1.add(login_layout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 120, 40));

        cancel.setBackground(new java.awt.Color(122, 122, 122));
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel_button.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        cancel_button.setForeground(new java.awt.Color(255, 255, 255));
        cancel_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel_button.setText("CANCEL");
        cancel.add(cancel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 120, 40));

        signUp.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(signUp, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sign_upbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_upbtMouseEntered
        sign_upbt.setBackground(bg1);
    }//GEN-LAST:event_sign_upbtMouseEntered

    private void login_layout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_layout1MouseClicked
     if (loginUser(email.getText(), pass.getText())) {
    if (!status.equals("Active")) {
        JOptionPane.showMessageDialog(null, "The account is not yet Active. Please contact the administrator");
    } else {
        JOptionPane.showMessageDialog(null, "Login Successfully!");
        if (type.equals("Admin")) {
            adminDashboard ad = new adminDashboard();
            ad.setVisible(true);
            this.dispose();
        } else if (type.equals("User")) {
            usersDashboard ud = new usersDashboard();
            ud.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "No account type found, contact the Administrator.");
        }
    }
    }else{
         JOptionPane.showMessageDialog(null, "Invalid Account!");
     }

    }//GEN-LAST:event_login_layout1MouseClicked

    private void login_layout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_layout1MouseEntered
      login_layout1.setBackground(login_b);
    }//GEN-LAST:event_login_layout1MouseEntered

    private void login_layout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_layout1MouseExited
      login_layout1.setBackground(bg);
    }//GEN-LAST:event_login_layout1MouseExited

    private void sign_upbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_upbtMouseExited
        sign_upbt.setBackground(signup);
    }//GEN-LAST:event_sign_upbtMouseExited

    private void sign_upbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_upbtMouseClicked
       signupForm sf= new signupForm();
        sf.setVisible(true);
        this.dispose();                    
    }//GEN-LAST:event_sign_upbtMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
    if(JOptionPane.showConfirmDialog(null, "Do you want to Exit?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
    System.exit(0);
}
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setBackground(signup_1);
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setBackground(signup);
    }//GEN-LAST:event_cancelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancel;
    private javax.swing.JLabel cancel_button;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logIn;
    private javax.swing.JLabel login_button1;
    private javax.swing.JPanel login_layout1;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel pass_label;
    private javax.swing.JLabel register_acc;
    private javax.swing.JPanel signUp;
    private javax.swing.JLabel sign_up;
    private javax.swing.JPanel sign_upbt;
    // End of variables declaration//GEN-END:variables
}
