/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patenio.dentalapp;

import config.connectDB;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class signupForm extends javax.swing.JFrame {

    /**
     * Creates new form signupForm
     */
    public signupForm() {
        initComponents();
    }
    
   public static String em;

public boolean duplicateCheck() {
    connectDB con = new connectDB();

    try {
        String query = "SELECT * FROM tbl_user WHERE email='" + email.getText() + "'";
        ResultSet resultSet = con.getData(query);
        if (resultSet.next()) {  
            em = resultSet.getString("email");
            if (em.equals(email.getText())) {
                JOptionPane.showMessageDialog(null, "Email already exists!");
                email.setText("");
                return true;
            }
        }
    } catch (SQLException ex) {
        System.out.println("Error: " + ex);
    }
    return false;
}   

    Color bg1 = new Color (153,153,153);
    Color login_b= new Color (82,107,136);
    Color bg= new Color (42,82,129);
    Color signup= new Color (122,122,122);
    Color cancel= new Color(89,111,137);
    Color signup_1= new Color (167,167,167);
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        logo_placement = new javax.swing.JLabel();
        logo_placement1 = new javax.swing.JLabel();
        logo_pic = new javax.swing.JLabel();
        users_table = new javax.swing.JPanel();
        lname_label = new javax.swing.JLabel();
        fname_label = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        phone_num = new javax.swing.JTextField();
        pass_label = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        email_label1 = new javax.swing.JLabel();
        conpass = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        conpass_label = new javax.swing.JLabel();
        phonenum_label = new javax.swing.JLabel();
        login_layout1 = new javax.swing.JPanel();
        cancel_button = new javax.swing.JLabel();
        login_layout = new javax.swing.JPanel();
        login_button1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        login_form = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginhere = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(42, 82, 129));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        logo.add(logo_placement, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -40, -1, -1));
        logo.add(logo_placement1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -40, -1, -1));

        logo_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/L.png"))); // NOI18N
        logo.add(logo_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, 0, -1, -1));

        mainPanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 530));

        users_table.setBackground(new java.awt.Color(213, 220, 233));
        users_table.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lname_label.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lname_label.setText("Last Name");
        users_table.add(lname_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        fname_label.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        fname_label.setText("First Name");
        users_table.add(fname_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        fname.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        fname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnameMouseClicked(evt);
            }
        });
        fname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                fnameCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        users_table.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 270, 40));

        lname.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnameMouseClicked(evt);
            }
        });
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        users_table.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 270, 40));

        phone_num.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        phone_num.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        phone_num.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phone_numMouseClicked(evt);
            }
        });
        phone_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_numActionPerformed(evt);
            }
        });
        users_table.add(phone_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 270, 40));

        pass_label.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        pass_label.setText("Password");
        users_table.add(pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        email.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        users_table.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 270, 40));

        email_label1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        email_label1.setText("Email");
        users_table.add(email_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        conpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        users_table.add(conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 270, 40));

        pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        users_table.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 270, 40));

        conpass_label.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        conpass_label.setText("Confirm Password");
        users_table.add(conpass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        phonenum_label.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        phonenum_label.setText("Phone number");
        users_table.add(phonenum_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        login_layout1.setBackground(new java.awt.Color(122, 122, 122));
        login_layout1.setForeground(new java.awt.Color(255, 255, 255));
        login_layout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_layout1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_layout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_layout1MouseExited(evt);
            }
        });
        login_layout1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel_button.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        cancel_button.setForeground(new java.awt.Color(255, 255, 255));
        cancel_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel_button.setText("CANCEL");
        login_layout1.add(cancel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        users_table.add(login_layout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 130, 40));

        login_layout.setBackground(new java.awt.Color(42, 82, 129));
        login_layout.setForeground(new java.awt.Color(42, 82, 129));
        login_layout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_layoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_layoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_layoutMouseExited(evt);
            }
        });
        login_layout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_button1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        login_button1.setForeground(new java.awt.Color(255, 255, 255));
        login_button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_button1.setText("SIGN UP");
        login_layout.add(login_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, -1));

        users_table.add(login_layout, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 130, 40));

        jPanel1.setBackground(new java.awt.Color(42, 82, 129));

        login_form.setBackground(new java.awt.Color(255, 255, 255));
        login_form.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        login_form.setForeground(new java.awt.Color(255, 255, 255));
        login_form.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_form.setText("REGISTRATION FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(login_form)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(login_form, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        users_table.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 410, 50));

        type.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        users_table.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 270, 40));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Type of User");
        users_table.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ALREADY HAVE AN ACCOUNT?");
        users_table.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        loginhere.setFont(new java.awt.Font("SansSerif", 2, 16)); // NOI18N
        loginhere.setForeground(new java.awt.Color(112, 156, 195));
        loginhere.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        loginhere.setText("LOGIN HERE");
        loginhere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginhereMouseClicked(evt);
            }
        });
        users_table.add(loginhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, -1, -1));

        mainPanel.add(users_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 550, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnameMouseClicked

    }//GEN-LAST:event_fnameMouseClicked

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
    
     
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameMouseClicked

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void phone_numMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phone_numMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_numMouseClicked

    private void phone_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_numActionPerformed

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseClicked

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void login_layoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_layoutMouseEntered
        login_layout.setBackground(login_b);
    }//GEN-LAST:event_login_layoutMouseEntered

    private void fnameCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_fnameCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameCaretPositionChanged

    private void login_layout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_layout1MouseEntered
        login_layout1.setBackground(signup_1);
    }//GEN-LAST:event_login_layout1MouseEntered

    private void login_layout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_layout1MouseClicked
      
      loginForm lf= new loginForm();
      lf.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_login_layout1MouseClicked

    private void login_layout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_layout1MouseExited
       login_layout1.setBackground(signup);
    }//GEN-LAST:event_login_layout1MouseExited

    private void login_layoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_layoutMouseClicked
    if (fname.getText().isEmpty() || lname.getText().isEmpty() || 
    phone_num.getText().isEmpty() || email.getText().isEmpty() || 
    pass.getText().isEmpty() || conpass.getText().isEmpty()) {

    JOptionPane.showMessageDialog(this, "All fields must be filled out.", "Input Error", JOptionPane.ERROR_MESSAGE);
    return;
}

if (!pass.getText().equals(conpass.getText())) { 
    JOptionPane.showMessageDialog(null, "Passwords do not match. Please try again.", "Input Error", JOptionPane.ERROR_MESSAGE);
    pass.setText("");
    conpass.setText("");
    return;
}

if (pass.getText().length() < 8) {
    JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long.", "Input Error", JOptionPane.ERROR_MESSAGE);
    pass.setText("");
    return;
}

if (duplicateCheck()) {
    System.out.println("Duplicate Exists");
    return; 
}

connectDB con = new connectDB();
int result = con.insertData("INSERT INTO tbl_user (fname, lname, phone_num, email, pass, u_type, status) " 
    + "VALUES('" + fname.getText() + "', '" + lname.getText() + "', '" + phone_num.getText() + "', '" 
    + email.getText() + "', '" + pass.getText() + "', '" + type.getSelectedItem() + "', 'Pending')");

if (result > 0) { 
    JOptionPane.showMessageDialog(null, "Sign up successfully! Wait for the Admin's approval for your registration.");
    loginForm lf = new loginForm();
    lf.setVisible(true);
    this.dispose();
} else {
    JOptionPane.showMessageDialog(null, "Connection Error");
}
    }//GEN-LAST:event_login_layoutMouseClicked

    private void login_layoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_layoutMouseExited
       login_layout.setBackground(bg);
    }//GEN-LAST:event_login_layoutMouseExited

    private void loginhereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginhereMouseClicked
       loginForm fm= new loginForm();
       fm.setVisible(true);
       this.dispose(); 
    }//GEN-LAST:event_loginhereMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancel_button;
    private javax.swing.JPasswordField conpass;
    private javax.swing.JLabel conpass_label;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email_label1;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel fname_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel lname_label;
    private javax.swing.JLabel login_button1;
    private javax.swing.JLabel login_form;
    private javax.swing.JPanel login_layout;
    private javax.swing.JPanel login_layout1;
    private javax.swing.JLabel loginhere;
    private javax.swing.JPanel logo;
    private javax.swing.JLabel logo_pic;
    private javax.swing.JLabel logo_placement;
    private javax.swing.JLabel logo_placement1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel pass_label;
    private javax.swing.JTextField phone_num;
    private javax.swing.JLabel phonenum_label;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JPanel users_table;
    // End of variables declaration//GEN-END:variables
}
