/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import patenio.dentalapp.*;
import java.awt.Color;

/**
 *
 * @author ride1
 */
public class adminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form usersDashboard
     */
    public adminDashboard() {
        initComponents();
    }
    
    
    Color panel = new Color (132,169,214);
    Color opanel= new Color (213,220,233);
    Color lout= new Color (240,240,240);
    Color white= new Color(255,255,255);
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        usersDashboard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        db = new javax.swing.JPanel();
        dboard = new javax.swing.JLabel();
        up = new javax.swing.JPanel();
        upage = new javax.swing.JLabel();
        rprt = new javax.swing.JPanel();
        report = new javax.swing.JLabel();
        admindb = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(42, 82, 129));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usersDashboard.setBackground(new java.awt.Color(213, 220, 233));
        usersDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/app.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        usersDashboard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 200, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avail.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        usersDashboard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 200, 200));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        usersDashboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, 200));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png"))); // NOI18N
        jLabel5.setText("jLabel2");
        usersDashboard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 200, 200));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("NOTE: MOCKUP ONLY");
        usersDashboard.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        mainPanel.add(usersDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 580, 410));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/side header.png"))); // NOI18N
        logo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -10, 790, -1));

        mainPanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 580, 60));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        db.setBackground(new java.awt.Color(204, 204, 204));
        db.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dbMouseExited(evt);
            }
        });

        dboard.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        dboard.setText("DASHBOARD");

        javax.swing.GroupLayout dbLayout = new javax.swing.GroupLayout(db);
        db.setLayout(dbLayout);
        dbLayout.setHorizontalGroup(
            dbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(dboard)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        dbLayout.setVerticalGroup(
            dbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dboard, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(db, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 60));

        up.setBackground(new java.awt.Color(204, 204, 204));
        up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                upMouseExited(evt);
            }
        });

        upage.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        upage.setText("USER PAGE");

        javax.swing.GroupLayout upLayout = new javax.swing.GroupLayout(up);
        up.setLayout(upLayout);
        upLayout.setHorizontalGroup(
            upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(upage)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        upLayout.setVerticalGroup(
            upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, 60));

        rprt.setBackground(new java.awt.Color(204, 204, 204));
        rprt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rprtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rprtMouseExited(evt);
            }
        });

        report.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        report.setText("REPORTS");

        javax.swing.GroupLayout rprtLayout = new javax.swing.GroupLayout(rprt);
        rprt.setLayout(rprtLayout);
        rprtLayout.setHorizontalGroup(
            rprtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rprtLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(report)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        rprtLayout.setVerticalGroup(
            rprtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rprtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(rprt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 190, 60));

        admindb.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        admindb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admindb.setText("ADMIN");
        jPanel1.add(admindb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 60, -1));

        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        admin.setText("jLabel2");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
        });
        jPanel1.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 440));

        logout.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("LOGOUT");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbMouseEntered
       db.setBackground(panel);
    }//GEN-LAST:event_dbMouseEntered

    private void dbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbMouseExited
       db.setBackground(opanel);
    }//GEN-LAST:event_dbMouseExited

    private void upMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upMouseEntered
       up.setBackground(panel);
    }//GEN-LAST:event_upMouseEntered

    private void upMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upMouseExited
        up.setBackground(opanel);
    }//GEN-LAST:event_upMouseExited

    private void rprtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rprtMouseEntered
        rprt.setBackground(panel);
    }//GEN-LAST:event_rprtMouseEntered

    private void rprtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rprtMouseExited
        rprt.setBackground(opanel);
    }//GEN-LAST:event_rprtMouseExited

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_adminMouseEntered

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(white);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setBackground(lout);
    }//GEN-LAST:event_logoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JLabel admindb;
    private javax.swing.JPanel db;
    private javax.swing.JLabel dboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel logo;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel report;
    private javax.swing.JPanel rprt;
    private javax.swing.JPanel up;
    private javax.swing.JLabel upage;
    private javax.swing.JPanel usersDashboard;
    // End of variables declaration//GEN-END:variables
}
